language: python
python:
  - "2.7"
  - "2.6"
#  - "pypy"
  - "3.3"
env:
  - REDMINE_VERSION=1.0.4
  - REDMINE_VERSION=1.1.3
install:
  - pip install -r requirements-test.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-2.6.txt; pip install unittest2 --use-mirrors; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python setup.py check; fi
  - ./tests/run_tests.py --redmine-version=$REDMINE_VERSION --check-rvm-ruby
