language: python
python:
  - "2.7"
#  - "2.6"
  - "pypy"
install:
  - pip install -r requirements-test.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --use-mirrors; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python setup.py check; fi
  - ./tests/run_tests.sh
